baseURL = "https://casperwang.pages.dev"
title = "casperwang"
theme = "hugo-PaperMod"
languageCode = "en-us"
hasCJKLanguage = true
enableEmoji = true
paginate = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
	title = "cwblog"
	description = "Live your dream"
	author = "casperwang"
	ShowReadingTime = true
  ShowWordCount = true

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/profile.php?id=100009793718487"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/casperwang1001/"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/casperwang"
  [[params.socialIcons]]
    name = "email"
    url = "https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=casperwang2014@gmail.com"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[[menu.main]]
	name = "About"
	url = "/about"
  weight = 1

[[menu.main]]
	name = "Writing"
	url = "/archives"
  weight = 2

[[menu.main]]
  name = "Traveling"
  url = "/traveling"
  weight = 3